### ISSUE TITLE
安装后出现这个样子

### ISSUE THREAD

**Issue by baiyuming** [HeyChioy/typecho-plugin-reward#2]
![image](https://cloud.githubusercontent.com/assets/13130499/26034717/5551c830-38f3-11e7-94cf-0b8026c0543a.png)

**Comment by kyuuseiryuu** [comment]
readme 注意事项 第一条就提到了。

博文后面多加几行空行回车就行了。

**Comment by baiyuming** [comment]
加了啊，还是不可以 ： [http://typecho.w3code.top/](http://typecho.w3code.top/)

**Comment by kyuuseiryuu** [comment]
博文编辑页面  **内容的最后几行** 截图看看。**光标** 停留在 **最后一个字符** 截图。
